# Generated by Django 4.2.3 on 2023-07-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertifika_turu', models.CharField(max_length=100)),
                ('fidan_adedi', models.IntegerField()),
                ('dikim_alani_secimi', models.CharField(choices=[('secim1', 'Seçenek 1'), ('secim2', 'Seçenek 2')], max_length=20)),
                ('saha', models.CharField(choices=[('secim1', 'Seçenek 1'), ('secim2', 'Seçenek 2')], max_length=20)),
                ('bagis_yapilacak_kurum_adi', models.CharField(max_length=100)),
                ('teslimat_turu', models.CharField(choices=[('eposta', 'E-Posta | Ücretsiz')], max_length=10)),
            ],
        ),
    ]
