# Generated by Django 4.2.3 on 2023-07-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.IntegerField()),
                ('plant_quantity', models.IntegerField()),
                ('plant_city', models.CharField(max_length=50)),
                ('plant_place_id', models.IntegerField()),
                ('certificate_title', models.CharField(max_length=100)),
                ('delivery_id', models.IntegerField()),
                ('delivery_title', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='CertificateApplication',
        ),
    ]
