# Generated by Django 4.2.3 on 2023-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_treecertificate_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('standart', 'Standart'), ('dugun_hediyesi', 'Düğün Hediyesi'), ('adima_bagis_yapmak_istiyorum', 'Adıma Bağış Yapmak İstiyorum'), ('kalkinma_yatirim_bankasi_gelir_getirici_fidan_dikim_projesi', 'Kalkınma Yatırım Bankası Gelir Getirici Fidan Dikim Projesi'), ('dugun_hediyesi', 'Düğün Hediyesi'), ('dugun_hediyesi', 'Düğün Hediyesi'), ('dugun_hediyesi', 'Düğün Hediyesi'), ('dugun_hediyesi', 'Düğün Hediyesi')], max_length=200),
        ),
    ]
