# Generated by Django 4.2.3 on 2023-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_treecertificate_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('standart', 'Standart'), ('dugun_hediyesi', 'Düğün Hediyesi'), ('adima_bagis_yapmak_istiyorum', 'Adıma Bağış Yapmak İstiyorum'), ('kalkinma_yatirim_bankasi_gelir_getirici_fidan_dikim_projesi', 'Kalkınma Yatırım Bankası Gelir Getirici Fidan Dikim Projesi'), ('mezuniyet', 'Mezuniyet'), ('köklerimiz_bu_topraklarda', 'Köklerimiz Bu Topraklarda'), ('Yetimler_için_fidan_bağişi', 'Yetimler İçin Fidan Bağışı'), ('hoşgeldin_bebek', 'Hoşgeldin Bebek '), ('bebek_hediyesi', 'Bebek Hediyesi (Bebeğimizin size hediyesi) '), ('sünnet_merasimi', 'Sünnet Merasimi '), ('doğum_günü', 'Doğum Günü - DAV '), ('bayram', 'Bayram  '), ('doğum_günü_kutlamasına_katılım', 'Doğum Günü Kutlamasına Katılım '), ('baş_sağliği', 'Baş Sağlığı (Merhum) '), ('baş_sağliği', 'Baş Sağlığı (Merhume) '), ('geçmiş_olsun', 'Geçmiş Olsun '), ('teşekkür', 'Teşekkür '), ('yeni_iş_tebriği', 'Yeni İş Tebriği '), ('yeni_unvan', 'Yeni Unvan '), ('açiliş', 'Açılış '), ('yeni_görev', 'Yeni Görev '), ('turkey_korea_friendship_forest', 'Turkey - Korea Friendship Forest '), ('yil_hatira_ormanlari', 'İTÜ 250. Yıl Hatıra Ormanları (3. kişiler için hediye) '), ('yil_hatira_ormanlari', 'İTÜ 250. Yıl Hatıra Ormanları '), ('çanakkale_mahmud_esad_coşan_hatira_ormani', 'Çanakkale Mahmud Esad Coşan Hatıra Ormanı '), ('tif_hatira_ormani_kendi_adima', 'TİF Hatıra Ormanı - Kendi Adıma '), ('tif_hatira_ormani_sevdiklerinize_hediye', 'TİF Hatıra Ormanı - Sevdiklerinize Hediye  '), ('türkiye_kore_dostluk_ormani', 'Türkiye-Kore Dostluk Ormanı '), ('hicri_yilbaşi', 'Hicri Yılbaşı '), ('serİzci_hatira_ormani', 'Serİzci Hatıra Ormanı '), ('asfa_hatira_ormani_sertifikasi', 'ASFA Hatıra Ormanı Sertifikası '), ('evlilik_yil_dönümü', 'Evlilik Yıl Dönümü '), ('ufka_yolculuk', 'Ufka Yolculuk '), ('kerbela_hatira_ormani ', 'Kerbela Hatıra Ormanı  '), ('mü_sosyal_gelişim_kulubü', 'MÜ Sosyal Gelişim Kulubü '), ('rootted_in_ourselves', 'ROOTED IN OURSELVES '), ('ufka_yolculuk_hatira_ormani', 'Ufka Yolculuk Hatıra Ormanı '), ('diş_kirasi_1444', 'Diş Kirası - 1444 '), ('hz_mevlana_hatira_ormani', 'Hz. Mevlana Hatıra Ormanı '), ('haci_ziyareti', 'Hacı Ziyareti '), ('diş_hekimleri_günü', 'Diş Hekimleri Günü '), ('bezmialem_vakif_üniversitesi__her_öğrenci_bir_fidan', 'Bezmialem Vakıf Üniversitesi-Her Öğrenci Bir Fidan '), ('pendik_mem_hatira_ormani', 'Pendik MEM Hatıra Ormanı '), ('Haydi Çocuklar Camiye', 'Haydi Çocuklar Camiye '), ('ihü_sosyal_sorumluluk_kulübü_hatıra_ormanı', 'İHÜ Sosyal Sorumluluk Kulübü Hatıra Ormanı '), ('istanbul_üniversitesi_psikoloji_kulübü_hatira_ormani', 'İstanbul Üniversitesi Psikoloji Kulübü Hatıra Ormanı '), ('kökü_bizde_yanan_ormanlarimizi_yeşertiyoruz', 'KÖKÜ BİZDE - Yanan Ormanlarımızı Yeşertiyoruz '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün '), ('dugun', 'Düğün ')], max_length=200),
        ),
    ]
