# Generated by Django 4.2.3 on 2023-08-09 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_treecertificate_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecertificate',
            name='bagis_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
