# Generated by Django 4.2.3 on 2023-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_treecertificate_bagis_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecertificate',
            name='tree_type',
            field=models.CharField(choices=[('zeytin', 'Zeytin Ağacı'), ('antep fistik', 'Antep Fıstık Ağacı')], max_length=50),
        ),
    ]
