# Generated by Django 4.2.3 on 2023-08-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_treecertificate_tree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecertificate',
            name='planting_area',
            field=models.CharField(choices=[('kilis', 'Kilis'), ('mardin', 'Mardin'), ('sanliurfa', 'Şanlıurfa'), ('canakkale', 'Çanakkale')], max_length=100),
        ),
    ]
