# Generated by Django 4.2.3 on 2023-07-24 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
    ]
