# Generated by Django 4.2.3 on 2023-07-24 12:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hakkimda',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='iletisim',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sonbagislar',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sss',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
