# Generated by Django 4.2.3 on 2023-07-25 00:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0002_alter_haber_content_alter_hakkimda_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uyelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
