# Generated by Django 4.2.3 on 2023-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0003_uyelik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyelik',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
